import Foundation

public class TvDeviceModel {
    public var host: String
    public var name: String
    
    public init(host: String, name: String) {
        self.host = host
        self.name = name
    }
    
    func getScript(for command: TvCommand) -> String {
        return ""
    }
    
    func open(app: TvApp) {
        
    }
}

public class TvSamsungModel: TvDeviceModel {
    override func getScript(for command: TvCommand) -> String {
        return "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\": \"Click\",\"DataOfCmd\":\"\(command.getSamsungKey())\",\"Option\": \"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}"
    }
    
    override func open(app: TvApp) {
        guard let url = URL(string: "http://\(host):8001/api/v2/applications/\(app.samsungAppID)") else { return }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        let task = URLSession.shared.dataTask(with: request) { _, _, _ in
        }
        task.resume()
    }
}

public class TvAndroidModel: TvDeviceModel {
    override func getScript(for command: TvCommand) -> String {
        return "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\": \"Click\",\"DataOfCmd\":\"\(command.getSamsungKey())\",\"Option\": \"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}"
    }
    
    override func open(app: TvApp) {
        guard let url = URL(string: "http://\(host):8001/api/v2/applications/\(app.samsungAppID)") else { return }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        let task = URLSession.shared.dataTask(with: request) { _, _, _ in
        }
        task.resume()
    }
}

public extension TvCommand {
    func getSamsungKey() -> String {
        switch self {
        case .KEY_MENU: return "KEY_MENU"
        case .KEY_UP: return "KEY_UP"
        case .KEY_DOWN: return "KEY_DOWN"
        case .KEY_LEFT: return "KEY_LEFT"
        case .KEY_RIGHT: return "KEY_RIGHT"
        case .KEY_VOLUP: return "KEY_VOLUP"
        case .KEY_VOLDOWN: return "KEY_VOLDOWN"
        case .KEY_0: return "KEY_0"
        case .KEY_1: return "KEY_1"
        case .KEY_2: return "KEY_2"
        case .KEY_3: return "KEY_3"
        case .KEY_4: return "KEY_4"
        case .KEY_5: return "KEY_5"
        case .KEY_6: return "KEY_6"
        case .KEY_7: return "KEY_7"
        case .KEY_8: return "KEY_8"
        case .KEY_9: return "KEY_9"
        case .KEY_10: return "KEY_10"
        case .KEY_11: return "KEY_11"
        case .KEY_12: return "KEY_12"
        case .KEY_MUTE: return "KEY_MUTE"
        case .KEY_CHDOWN: return "KEY_CHDOWN"
        case .KEY_CHUP: return "KEY_CHUP"
        case .KEY_PRECH: return "KEY_PRECH"
        case .KEY_GREEN: return "KEY_GREEN"
        case .KEY_YELLOW: return "KEY_YELLOW"
        case .KEY_CYAN: return "KEY_CYAN"
        case .KEY_ADDDEL: return "KEY_ADDDEL"
        case .KEY_SOURCE: return "KEY_SOURCE"
        case .KEY_INFO: return "KEY_INFO"
        case .KEY_PIP_ONOFF: return "KEY_PIP_ONOFF"
        case .KEY_PIP_SWAP: return "KEY_PIP_SWAP"
        case .KEY_PLUS100: return "KEY_PLUS100"
        case .KEY_CAPTION: return "KEY_CAPTION"
        case .KEY_PMODE: return "KEY_PMODE"
        case .KEY_TTX_MIX: return "KEY_TTX_MIX"
        case .KEY_TV: return "KEY_TV"
        case .KEY_PICTURE_SIZE: return "KEY_PICTURE_SIZE"
        case .KEY_AD: return "KEY_AD"
        case .KEY_PIP_SIZE: return "KEY_PIP_SIZE"
        case .KEY_MAGIC_CHANNEL: return "KEY_MAGIC_CHANNEL"
        case .KEY_PIP_SCAN: return "KEY_PIP_SCAN"
        case .KEY_PIP_CHUP: return "KEY_PIP_CHUP"
        case .KEY_PIP_CHDOWN: return "KEY_PIP_CHDOWN"
        case .KEY_DEVICE_CONNECT: return "KEY_DEVICE_CONNECT"
        case .KEY_HELP: return "KEY_HELP"
        case .KEY_ANTENA: return "KEY_ANTENA"
        case .KEY_CONVERGENCE: return "KEY_CONVERGENCE"
        case .KEY_AUTO_PROGRAM: return "KEY_AUTO_PROGRAM"
        case .KEY_FACTORY: return "KEY_FACTORY"
        case .KEY_3SPEED: return "KEY_3SPEED"
        case .KEY_RSURF: return "KEY_RSURF"
        case .KEY_ASPECT: return "KEY_ASPECT"
        case .KEY_TOPMENU: return "KEY_TOPMENU"
        case .KEY_GAME: return "KEY_GAME"
        case .KEY_QUICK_REPLAY: return "KEY_QUICK_REPLAY"
        case .KEY_STILL_PICTURE: return "KEY_STILL_PICTURE"
        case .KEY_DTV: return "KEY_DTV"
        case .KEY_FAVCH: return "KEY_FAVCH"
        case .KEY_REWIND: return "KEY_REWIND"
        case .KEY_STOP: return "KEY_STOP"
        case .KEY_PLAY: return "KEY_PLAY"
        case .KEY_FF: return "KEY_FF"
        case .KEY_REC: return "KEY_REC"
        case .KEY_PAUSE: return "KEY_PAUSE"
        case .KEY_TOOLS: return "KEY_TOOLS"
        case .KEY_INSTANT_REPLAY: return "KEY_INSTANT_REPLAY"
        case .KEY_LINK: return "KEY_LINK"
        case .KEY_FF_: return "KEY_FF_"
        case .KEY_GUIDE: return "KEY_GUIDE"
        case .KEY_REWIND_: return "KEY_REWIND_"
        case .KEY_ANGLE: return "KEY_ANGLE"
        case .KEY_RESERVED1: return "KEY_RESERVED1"
        case .KEY_ZOOM1: return "KEY_ZOOM1"
        case .KEY_PROGRAM: return "KEY_PROGRAM"
        case .KEY_BOOKMARK: return "KEY_BOOKMARK"
        case .KEY_DISC_MENU: return "KEY_DISC_MENU"
        case .KEY_PRINT: return "KEY_PRINT"
        case .KEY_RETURN: return "KEY_RETURN"
        case .KEY_SUB_TITLE: return "KEY_SUB_TITLE"
        case .KEY_CLEAR: return "KEY_CLEAR"
        case .KEY_VCHIP: return "KEY_VCHIP"
        case .KEY_REPEAT: return "KEY_REPEAT"
        case .KEY_DOOR: return "KEY_DOOR"
        case .KEY_OPEN: return "KEY_OPEN"
        case .KEY_WHEEL_LEFT: return "KEY_WHEEL_LEFT"
        case .KEY_POWER: return "KEY_POWER"
        case .KEY_SLEEP: return "KEY_SLEEP"
        case .KEY_DMA: return "KEY_DMA"
        case .KEY_TURBO: return "KEY_TURBO"
        case .KEY_FM_RADIO: return "KEY_FM_RADIO"
        case .KEY_DVR_MENU: return "KEY_DVR_MENU"
        case .KEY_MTS: return "KEY_MTS"
        case .KEY_PCMODE: return "KEY_PCMODE"
        case .KEY_TTX_SUBFACE: return "KEY_TTX_SUBFACE"
        case .KEY_CH_LIST: return "KEY_CH_LIST"
        case .KEY_RED: return "KEY_RED"
        case .KEY_DNIe: return "KEY_DNIe"
        case .KEY_SRS: return "KEY_SRS"
        case .KEY_CONVERT_AUDIO_MAINSUB: return "KEY_CONVERT_AUDIO_MAINSUB"
        case .KEY_MDC: return "KEY_MDC"
        case .KEY_SEFFECT: return "KEY_SEFFECT"
        case .KEY_DVR: return "KEY_DVR"
        case .KEY_DTV_SIGNAL: return "KEY_DTV_SIGNAL"
        case .KEY_LIVE: return "KEY_LIVE"
        case .KEY_PERPECT_FOCUS: return "KEY_PERPECT_FOCUS"
        case .KEY_HOME: return "KEY_HOME"
        case .KEY_ESAVING: return "KEY_ESAVING"
        case .KEY_WHEEL_RIGHT: return "KEY_WHEEL_RIGHT"
        case .KEY_CONTENTS: return "KEY_CONTENTS"
        case .KEY_VCR_MODE: return "KEY_VCR_MODE"
        case .KEY_CATV_MODE: return "KEY_CATV_MODE"
        case .KEY_DSS_MODE: return "KEY_DSS_MODE"
        case .KEY_TV_MODE: return "KEY_TV_MODE"
        case .KEY_DVD_MODE: return "KEY_DVD_MODE"
        case .KEY_STB_MODE: return "KEY_STB_MODE"
        case .KEY_CALLER_ID: return "KEY_CALLER_ID"
        case .KEY_SCALE: return "KEY_SCALE"
        case .KEY_ZOOM_MOVE: return "KEY_ZOOM_MOVE"
        case .KEY_CLOCK_DISPLAY: return "KEY_CLOCK_DISPLAY"
        case .KEY_AV1: return "KEY_AV1"
        case .KEY_SVIDEO1: return "KEY_SVIDEO1"
        case .KEY_COMPONENT1: return "KEY_COMPONENT1"
        case .KEY_SETUP_CLOCK_TIMER: return "KEY_SETUP_CLOCK_TIMER"
        case .KEY_COMPONENT2: return "KEY_COMPONENT2"
        case .KEY_MAGIC_BRIGHT: return "KEY_MAGIC_BRIGHT"
        case .KEY_DVI: return "KEY_DVI"
        case .KEY_HDMI: return "KEY_HDMI"
        case .KEY_W_LINK: return "KEY_W_LINK"
        case .KEY_DTV_LINK: return "KEY_DTV_LINK"
        case .KEY_APP_LIST: return "KEY_APP_LIST"
        case .KEY_BACK_MHP: return "KEY_BACK_MHP"
        case .KEY_ALT_MHP: return "KEY_ALT_MHP"
        case .KEY_DNSe: return "KEY_DNSe"
        case .KEY_RSS: return "KEY_RSS"
        case .KEY_ENTERTAINMENT: return "KEY_ENTERTAINMENT"
        case .KEY_ID_INPUT: return "KEY_ID_INPUT"
        case .KEY_ID_SETUP: return "KEY_ID_SETUP"
        case .KEY_ANYNET: return "KEY_ANYNET"
        case .KEY_POWEROFF: return "KEY_POWEROFF"
        case .KEY_POWERON: return "KEY_POWERON"
        case .KEY_ANYVIEW: return "KEY_ANYVIEW"
        case .KEY_MS: return "KEY_MS"
        case .KEY_MORE: return "KEY_MORE"
        case .KEY_PANNEL_POWER: return "KEY_PANNEL_POWER"
        case .KEY_PANNEL_CHUP: return "KEY_PANNEL_CHUP"
        case .KEY_PANNEL_CHDOWN: return "KEY_PANNEL_CHDOWN"
        case .KEY_PANNEL_VOLUP: return "KEY_PANNEL_VOLUP"
        case .KEY_PANNEL_VOLDOW: return "KEY_PANNEL_VOLDOW"
        case .KEY_PANNEL_ENTER: return "KEY_PANNEL_ENTER"
        case .KEY_PANNEL_MENU: return "KEY_PANNEL_MENU"
        case .KEY_PANNEL_SOURCE: return "KEY_PANNEL_SOURCE"
        case .KEY_AV2: return "KEY_AV2"
        case .KEY_AV3: return "KEY_AV3"
        case .KEY_SVIDEO2: return "KEY_SVIDEO2"
        case .KEY_SVIDEO3: return "KEY_SVIDEO3"
        case .KEY_ZOOM2: return "KEY_ZOOM2"
        case .KEY_PANORAMA: return "KEY_PANORAMA"
        case .KEY_4_3: return "KEY_4_3"
        case .KEY_16_9: return "KEY_16_9"
        case .KEY_DYNAMIC: return "KEY_DYNAMIC"
        case .KEY_STANDARD: return "KEY_STANDARD"
        case .KEY_MOVIE1: return "KEY_MOVIE1"
        case .KEY_CUSTOM: return "KEY_CUSTOM"
        case .KEY_AUTO_ARC_RESET: return "KEY_AUTO_ARC_RESET"
        case .KEY_AUTO_ARC_LNA_ON: return "KEY_AUTO_ARC_LNA_ON"
        case .KEY_AUTO_ARC_LNA_OFF: return "KEY_AUTO_ARC_LNA_OFF"
        case .KEY_AUTO_ARC_ANYNET_MODE_OK: return "KEY_AUTO_ARC_ANYNET_MODE_OK"
        case .KEY_AUTO_ARC_ANYNET_AUTO_START: return "KEY_AUTO_ARC_ANYNET_AUTO_START"
        case .KEY_AUTO_FORMAT: return "KEY_AUTO_FORMAT"
        case .KEY_DNET: return "KEY_DNET"
        case .KEY_HDMI1: return "KEY_HDMI1"
        case .KEY_AUTO_ARC_CAPTION_ON: return "KEY_AUTO_ARC_CAPTION_ON"
        case .KEY_AUTO_ARC_CAPTION_OFF: return "KEY_AUTO_ARC_CAPTION_OFF"
        case .KEY_AUTO_ARC_PIP_DOUBLE: return "KEY_AUTO_ARC_PIP_DOUBLE"
        case .KEY_AUTO_ARC_PIP_LARGE: return "KEY_AUTO_ARC_PIP_LARGE"
        case .KEY_AUTO_ARC_PIP_SMALL: return "KEY_AUTO_ARC_PIP_SMALL"
        case .KEY_AUTO_ARC_PIP_WIDE: return "KEY_AUTO_ARC_PIP_WIDE"
        case .KEY_AUTO_ARC_PIP_LEFT_TOP: return "KEY_AUTO_ARC_PIP_LEFT_TOP"
        case .KEY_AUTO_ARC_PIP_RIGHT_TOP: return "KEY_AUTO_ARC_PIP_RIGHT_TOP"
        case .KEY_AUTO_ARC_PIP_LEFT_BOTTOM: return "KEY_AUTO_ARC_PIP_LEFT_BOTTOM"
        case .KEY_AUTO_ARC_PIP_RIGHT_BOTTOM: return "KEY_AUTO_ARC_PIP_RIGHT_BOTTOM"
        case .KEY_AUTO_ARC_PIP_CH_CHANGE: return "KEY_AUTO_ARC_PIP_CH_CHANGE"
        case .KEY_AUTO_ARC_AUTOCOLOR_SUCCESS: return "KEY_AUTO_ARC_AUTOCOLOR_SUCCESS"
        case .KEY_AUTO_ARC_AUTOCOLOR_FAIL: return "KEY_AUTO_ARC_AUTOCOLOR_FAIL"
        case .KEY_AUTO_ARC_C_FORCE_AGING: return "KEY_AUTO_ARC_C_FORCE_AGING"
        case .KEY_AUTO_ARC_USBJACK_INSPECT: return "KEY_AUTO_ARC_USBJACK_INSPECT"
        case .KEY_AUTO_ARC_JACK_IDENT: return "KEY_AUTO_ARC_JACK_IDENT"
        case .KEY_NINE_SEPERATE: return "KEY_NINE_SEPERATE"
        case .KEY_ZOOM_IN: return "KEY_ZOOM_IN"
        case .KEY_ZOOM_OUT: return "KEY_ZOOM_OUT"
        case .KEY_MIC: return "KEY_MIC"
        case .KEY_HDMI2: return "KEY_HDMI2"
        case .KEY_HDMI3: return "KEY_HDMI3"
        case .KEY_AUTO_ARC_CAPTION_KOR: return "KEY_AUTO_ARC_CAPTION_KOR"
        case .KEY_AUTO_ARC_CAPTION_ENG: return "KEY_AUTO_ARC_CAPTION_ENG"
        case .KEY_AUTO_ARC_PIP_SOURCE_CHANGE: return "KEY_AUTO_ARC_PIP_SOURCE_CHANGE"
        case .KEY_HDMI4: return "KEY_HDMI4"
        case .KEY_AUTO_ARC_ANTENNA_AIR: return "KEY_AUTO_ARC_ANTENNA_AIR"
        case .KEY_AUTO_ARC_ANTENNA_CABLE: return "KEY_AUTO_ARC_ANTENNA_CABLE"
        case .KEY_AUTO_ARC_ANTENNA_SATELLITE: return "KEY_AUTO_ARC_ANTENNA_SATELLITE"
        case .KEY_EXT1: return "KEY_EXT1"
        case .KEY_EXT2: return "KEY_EXT2"
        case .KEY_EXT3: return "KEY_EXT3"
        case .KEY_EXT4: return "KEY_EXT4"
        case .KEY_EXT5: return "KEY_EXT5"
        case .KEY_EXT6: return "KEY_EXT6"
        case .KEY_EXT7: return "KEY_EXT7"
        case .KEY_EXT8: return "KEY_EXT8"
        case .KEY_EXT9: return "KEY_EXT9"
        case .KEY_EXT10: return "KEY_EXT10"
        case .KEY_EXT11: return "KEY_EXT11"
        case .KEY_EXT12: return "KEY_EXT12"
        case .KEY_EXT13: return "KEY_EXT13"
        case .KEY_EXT14: return "KEY_EXT14"
        case .KEY_EXT15: return "KEY_EXT15"
        case .KEY_EXT16: return "KEY_EXT16"
        case .KEY_EXT17: return "KEY_EXT17"
        case .KEY_EXT18: return "KEY_EXT18"
        case .KEY_EXT19: return "KEY_EXT19"
        case .KEY_EXT20: return "KEY_EXT20"
        case .KEY_EXT21: return "KEY_EXT21"
        case .KEY_EXT22: return "KEY_EXT22"
        case .KEY_EXT23: return "KEY_EXT23"
        case .KEY_EXT24: return "KEY_EXT24"
        case .KEY_EXT25: return "KEY_EXT25"
        case .KEY_EXT26: return "KEY_EXT26"
        case .KEY_EXT27: return "KEY_EXT27"
        case .KEY_EXT28: return "KEY_EXT28"
        case .KEY_EXT29: return "KEY_EXT29"
        case .KEY_EXT30: return "KEY_EXT30"
        case .KEY_EXT31: return "KEY_EXT31"
        case .KEY_EXT32: return "KEY_EXT32"
        case .KEY_EXT33: return "KEY_EXT33"
        case .KEY_EXT34: return "KEY_EXT34"
        case .KEY_EXT35: return "KEY_EXT35"
        case .KEY_EXT36: return "KEY_EXT36"
        case .KEY_EXT37: return "KEY_EXT37"
        case .KEY_EXT38: return "KEY_EXT38"
        case .KEY_EXT39: return "KEY_EXT39"
        case .KEY_EXT40: return "KEY_EXT40"
        case .KEY_EXT41: return "KEY_EXT41"
        case .KEY_NEXT: return "KEY_NEXT"
        case .KEY_PREV: return "KEY_PREV"
        }
    }
}
